// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";


const { NODE_ENV, LOCAL_DB_URL, NEON_DIRECT_URL } = process.env

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: NODE_ENV === 'dev' ? LOCAL_DB_URL : NODE_ENV === 'prod' ? NEON_DIRECT_URL : null ,
  },
});
